services:

  web:
    build: .
    container_name: vite_gourmand_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: mysql
      DB_NAME: vite_gourmand
      DB_USER: root
      DB_PASSWORD: root
    depends_on:
      - mysql

  mysql:
    image: mysql:8.4
    container_name: vite_gourmand_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./SQL/table.sql:/docker-entrypoint-initdb.d/01-table.sql:ro

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: vite_gourmand_phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql

volumes:
  mysql_data: